apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-ui-config
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: prod
    app.kubernetes.io/component: ui-config
data:
  message: "Running from the prod environment."
