apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-qa
nameSuffix: -qa
resources:
#  - ../../bases/backend
  - ../../bases/frontend
#  - ../../bases/cache
  - namespace.yaml
  - ingress.yaml
  - ui-config.yaml
transformers:
  - labels.yaml
patches:
  - path: frontend-replicas.yaml
